/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SalesImport } from './routes/sales'
import { Route as IndexImport } from './routes/index'
import { Route as SalesIndexImport } from './routes/sales.index'
import { Route as SalesInvoiceIdImport } from './routes/sales.$invoiceId'

// Create/Update Routes

const SalesRoute = SalesImport.update({
  path: '/sales',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SalesIndexRoute = SalesIndexImport.update({
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)

const SalesInvoiceIdRoute = SalesInvoiceIdImport.update({
  path: '/$invoiceId',
  getParentRoute: () => SalesRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesImport
      parentRoute: typeof rootRoute
    }
    '/sales/$invoiceId': {
      id: '/sales/$invoiceId'
      path: '/$invoiceId'
      fullPath: '/sales/$invoiceId'
      preLoaderRoute: typeof SalesInvoiceIdImport
      parentRoute: typeof SalesImport
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexImport
      parentRoute: typeof SalesImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  SalesRoute: SalesRoute.addChildren({ SalesInvoiceIdRoute, SalesIndexRoute }),
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/sales"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/sales": {
      "filePath": "sales.tsx",
      "children": [
        "/sales/$invoiceId",
        "/sales/"
      ]
    },
    "/sales/$invoiceId": {
      "filePath": "sales.$invoiceId.tsx",
      "parent": "/sales"
    },
    "/sales/": {
      "filePath": "sales.index.tsx",
      "parent": "/sales"
    }
  }
}
ROUTE_MANIFEST_END */
